version: "3.8"

services:
  logging-house:
    image: ghcr.io/ids-basecamp/clearinghouse/ch-app:2.0.0-alpha.12
    environment:
      CH_APP_LOG_LEVEL: INFO
      CH_APP_DATABASE_URL: postgres://clearing:password@ch-db:5432/clearing
      CH_APP_P12_PATH: /run/secrets/certificate.p12
      CH_APP_P12_PASSWORD: password
      CH_APP_DAPS_TOKEN_URL: https://${DAPS_DOMAIN}/realms/DAPS/protocol/openid-connect/token
      CH_APP_DAPS_CERTS_URL: https://${DAPS_DOMAIN}/realms/DAPS/protocol/openid-connect/certs
      CH_APP_TOKEN_SCOPE: "https://daps.dev.mobility-dataspace.eu/realms/DAPS"
      CH_APP_STATIC_PROCESS_OWNER: "MDS"
      CH_APP_ISSUER: https://clearing.dev.mobility-dataspace.eu
    volumes:
      - ./certificate.p12:/run/secrets/certificate.p12

  ch-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: clearing
      POSTGRES_DB: clearing
